### ISSUE TITLE
Automated Unit testing

### ISSUE THREAD

**Issue by n-widmer** [EanDodge/Software-Engineering-Delta#45]

**Comment by OrionC10** [comment]
Try to test
-player.drawPlayer()
-player.movePlayer()
-player.testCollision()
-player.checkCollisionEnemies()
-input?
-constructor?

How many of these can we test every time the game is started? Can we make an instance of game before the actual game and somehow pull information from it without actually drawing the sprites?

If they cant be ran every time how do we use chrome driver to test these?

**Comment by OrionC10** [comment]
This issue is too broad to be "completed". We need to write tests as we make the functions.

I managed to make unit tests for player methods, move, check collision, check collision enemy, and constructor.

Going forward we need to assign specific unit tests to be written, something this broad can not be definitively closed.
